name: Test and deploy PR from fork

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.id }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: ['Build PR From Fork']
    types: ['completed']
    branches-ignore: ['master']

jobs:
  prepare_jobs:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    outputs:
      pr_commit_sha: ${{ steps.get_pr_info.outputs.pr_commit_sha }}
    steps:
      - name: Download PR info
        uses: dawidd6/action-download-artifact@575b1e4167df67acf7e692af784566618b23c71e # v2.17.0
        with:
          workflow: build-fork.yml
          run_id: ${{ github.event.workflow_run.id }}
          workflow_conclusion: success
          name: pr
          path: ./

      - name: Get PR head commit sha
        id: get_pr_info
        run: |
          echo "::set-output name=pr_commit_sha::$(cat SHA)"
          echo "::set-output name=pr_number::$(cat NUM)"

  prerelease:
    runs-on: ubuntu-latest
    needs: ['prepare_jobs']
    env:
      pr_commit_sha: ${{ needs.prepare_jobs.outputs.pr_commit_sha }}
      pr_number: ${{ needs.prepare_jobs.outputs.pr_number }}
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3.0.0
        with:
          token: ${{ secrets.BOT_TOKEN }}

      - name: Download math-utils build
        uses: dawidd6/action-download-artifact@575b1e4167df67acf7e692af784566618b23c71e # v2.17.0
        with:
          workflow: build-fork.yml
          run_id: ${{ github.event.workflow_run.id }}
          workflow_conclusion: success
          name: math-utils
          path: packages/math-utils/dist
      - name: Download contract-helpers build
        uses: dawidd6/action-download-artifact@575b1e4167df67acf7e692af784566618b23c71e # v2.17.0
        with:
          workflow: build-fork.yml
          run_id: ${{ github.event.workflow_run.id }}
          workflow_conclusion: success
          name: contract-helpers
          path: packages/contract-helpers/dist

      - name: prerelease
        run: |
          yarn release:canary \
          --yes --no-verify-access \
          --dist-tag ${{ env.pr_commit_sha }} --preid ${{ env.pr_commit_sha }} \
          | tee __publish-log.txt

      - name: Comment on PR
        if: always()
        uses: ./.github/actions/pr-comment
        with:
          PR_NUMBER: ${{ env.pr_number }}
